# Generated by Django 4.2.3 on 2023-07-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emp_app.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emp_app.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
